modLoader="javafml" 
loaderVersion="[41,)"
license="GPL3"
issueTrackerURL="https://github.com/MrCrayfish/Catalogue/issues"

[[mods]]
modId="catalogue"
version="1.7.0"
displayName="Catalogue"
authors="MrCrayfish"
logoFile="catalogue_icon.png"
logoBlur=false
displayURL="https://www.curseforge.com/minecraft/mc-mods/catalogue"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=catalogue"
description="Updates Forge's mod list with a new and improved design"
credits="Hatsondogs for creating icons"

[[dependencies.catalogue]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.catalogue]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.catalogue]
    catalogueImageIcon="catalogue_icon.png"
    catalogueBackground="catalogue_background.png"
